// frontend-vue/src/components/layout/Header.vue
<script setup lang="ts">
defineProps<{ title: string }>();
</script>

<template>
  <header class="header">
    <div class="header-title">{{ title }}</div>
    <div class="header-search">
      <input type="text" placeholder="Search..." />
    </div>
    <div class="header-actions">
      <button class="header-bell" aria-label="Notifications">&#x1F514;</button>
      <div class="header-avatar">&#x1F354;</div>
      <span class="header-username">Delicious Burger</span>
    </div>
  </header>
</template>

// frontend/src/components/layout/Header.jsx
export function Header({ title }) {
  return (
    <header className="header">
      <h1 className="header-title">{title}</h1>
      <div className="header-right">
        <input type="text" className="header-search" placeholder="Search..." />
        <button className="header-bell" title="Notifications">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#64748b" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9" />
            <path d="M13.73 21a2 2 0 0 1-3.46 0" />
          </svg>
        </button>
        <div className="header-user">
          <div className="header-avatar">CA</div>
          <span>Centuri Admin</span>
        </div>
      </div>
    </header>
  );
}
