// frontend-vue/src/components/layout/Layout.vue
<script setup lang="ts">
import Sidebar from './Sidebar.vue';
import Header from './Header.vue';

defineProps<{ title?: string }>();
</script>

<template>
  <div class="app-shell">
    <Sidebar />
    <div class="main-area">
      <Header :title="title ?? 'Dashboard'" />
      <div class="content">
        <slot />
      </div>
    </div>
  </div>
</template>

// frontend/src/components/layout/Layout.jsx
import { Sidebar } from './Sidebar';
import { Header } from './Header';

export function Layout({ title, children }) {
  return (
    <div className="app-shell">
      <Sidebar />
      <div className="main-area">
        <Header title={title} />
        <div className="content">{children}</div>
      </div>
    </div>
  );
}
